# Generated by Django 4.2.4 on 2023-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productcls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=100)),
                ('gheymat', models.CharField(max_length=20)),
                ('tosif', models.TextField(max_length=40)),
                ('aks', models.CharField(max_length=20)),
            ],
        ),
    ]
